"""add branch password_hash

Revision ID: 2653a2845e84
Revises: f1b8b0ded413
Create Date: 2026-07-25 20:19:20.650872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2653a2845e84'
down_revision: Union[str, None] = 'f1b8b0ded413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch', 'password_hash')
    # ### end Alembic commands ###
