"""add branch camera_stream_url

Revision ID: 2d14339918a2
Revises: 97f8513a95e8
Create Date: 2026-07-27 14:34:46.714345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d14339918a2'
down_revision: Union[str, None] = '97f8513a95e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('camera_stream_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch', 'camera_stream_url')
    # ### end Alembic commands ###
