"""add branch code, frame and lens product tables

Revision ID: 5ce9f9b74c84
Revises: 9631e7b94706
Create Date: 2026-07-24 18:15:04.556908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce9f9b74c84'
down_revision: Union[str, None] = '9631e7b94706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('code', sa.String(), nullable=True))
     # 2. backfill existing rows — auto-generate from name, e.g. "Main Branch" -> "MAIN"
    op.execute("""
        UPDATE branch
        SET code = UPPER(LEFT(REGEXP_REPLACE(name, '[^a-zA-Z0-9]', '', 'g'), 6)) || '_' || LEFT(id::text, 4)
        WHERE code IS NULL
    """)

    # 3. now tighten to NOT NULL + UNIQUE
    op.alter_column('branch', 'code', nullable=False)
    op.create_unique_constraint('uq_branch_code', 'branch', ['code'])
    op.create_index(op.f('ix_branch_code'), 'branch', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branch_code'), table_name='branch')
    op.drop_column('branch', 'code')
    # ### end Alembic commands ###
