"""add purchase_count and loyalty_points to customer

Revision ID: 9631e7b94706
Revises: fdf9d43a1d3e
Create Date: 2026-07-13 20:56:00.184319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9631e7b94706'
down_revision: Union[str, None] = 'fdf9d43a1d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('customer', sa.Column('purchase_count', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('loyalty_points', sa.Integer(), nullable=True))

    # Backfill existing rows before enforcing NOT NULL
    op.execute("UPDATE customer SET purchase_count = 0 WHERE purchase_count IS NULL")
    op.execute("UPDATE customer SET loyalty_points = 0 WHERE loyalty_points IS NULL")

    op.alter_column('customer', 'purchase_count', nullable=False)
    op.alter_column('customer', 'loyalty_points', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'loyalty_points')
    op.drop_column('customer', 'purchase_count')
    # ### end Alembic commands ###
