"""add customer discount_level

Revision ID: 97f8513a95e8
Revises: 2653a2845e84
Create Date: 2026-07-26 19:19:16.270091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f8513a95e8'
down_revision: Union[str, None] = '2653a2845e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('discount_level', sa.Integer(), nullable=True))
    op.execute("UPDATE customer SET discount_level = 0 WHERE discount_level IS NULL")
    op.alter_column('customer', 'discount_level', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'discount_level')
    # ### end Alembic commands ###
