"""add performance indexes on sale and product branch_id/created_at

Revision ID: a4003fe2bd1c
Revises: 2d14339918a2
Create Date: 2026-07-29 18:12:04.052845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4003fe2bd1c'
down_revision: Union[str, None] = '2d14339918a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_frame_products_branch_id'), 'frame_products', ['branch_id'], unique=False)
    op.create_index(op.f('ix_lens_specs_branch_id'), 'lens_specs', ['branch_id'], unique=False)
    op.create_index(op.f('ix_sale_branch_id'), 'sale', ['branch_id'], unique=False)
    op.create_index(op.f('ix_sale_created_at'), 'sale', ['created_at'], unique=False)
    op.create_index(op.f('ix_sale_line_item_sale_id'), 'sale_line_item', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_line_item_sale_id'), table_name='sale_line_item')
    op.drop_index(op.f('ix_sale_created_at'), table_name='sale')
    op.drop_index(op.f('ix_sale_branch_id'), table_name='sale')
    op.drop_index(op.f('ix_lens_specs_branch_id'), table_name='lens_specs')
    op.drop_index(op.f('ix_frame_products_branch_id'), table_name='frame_products')
    # ### end Alembic commands ###
